### ISSUE TITLE
does it exist already ?

### ISSUE THREAD

**Issue by ffred** [robin-raymond/zax.io#1]
Hi,
you talk about Jai for inspiration (maybe you could add Odin or even more Zig), but is Zax like Jai and only visible to a few and won't be public before years or does it exist somewhere ? or are you just creating it ..?
well, the actual doc is interesting, but if there's no code.....

**Comment by robin-raymond** [comment]
Had the project on the back burner for years but I'm literally just starting to actually "do it". Too many projects, too little time. I'm writing up the documentation so I can know the scope of what I want to code, and provide myself some needed documentation for the parser/generator and what features I will prioritize. The inspiration from Jai was mostly to just do it; I do also like some of the concepts as I think they solve some issues in clever ways but I would want a few things differently since I don't primarily do game coding so my priorities are a bit different. Code will be fully visible as I do it. First pass will function first and like all code will always suck in its first iteration as I sort out the design. So yes, no code yet. I didn't expect anyone to notice it for a bit so I took it for granted I'd have some time to prove it out. Should be fun to write the compiler but I wouldn't expect anyone to take it serious until the code is there to back it up, even though I'm serious about putting code against it. Thanks!

**Comment by ffred** [comment]
well, github search function is really bad, but sometimes with a little chance you can discover new things.. :-)
ok, thanks.

**Comment by robin-raymond** [comment]
Just as an update to anyone who might find this issue. The prototype compiler is being developed here:
[Zax Compiler](https://github.com/robin-raymond/zax-compiler)

It's extremely early stages right now as it's being actively built.
